packages:
  - packages/*
  - apps/*
  - dev-dashboard

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@nx/angular-rspack-compiler'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver
